package com.github.bartoszpogoda.thesis.teamchallengeapi.core.exception;

public enum ExceptionCode {
    UNAUTHORIZED,
    VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_USED,
    FACILITY_NOT_FOUND,
    UNKNOWN_DISCIPLINE,
    PLAYER_ALREADY_EXISTS,
    INTERNAL_SERVER_ERROR,
    PLAYER_NOT_FOUND,
    UNKNOWN_REGION,
    PLAYER_ALREADY_IN_TEAM,
    TEAM_NOT_FOUND,
    TEAM_INVITATION_NOT_FOUND,
    ALREADY_INVITED,
    IMAGE_NOT_FOUND,
    POSITION_NOT_FOUND,
    PLAYER_NOT_IN_TEAM,
    NOT_MANAGER,
    INVALID_OPERATION_EXCEPTION, CHALLENGE_NOT_FOUND, PLACE_TIME_OFFER_NOT_FOUND, TEAM_ALREADY_CHALLENGED, TEAM_NOT_IN_CHALLENGE, RESULT_NOT_FOUND, TEAM_IS_FULL, ACTION_FORBIDDEN, TEAM_REVIEW_NOT_FOUND;
}
